[package]
name = "lazy-pipe"
version = "0.1.0"
description = "Chain closures into a pipeline"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
license = "MIT"
repository = "https://github.com/ksxrustcrates/lazy-pipe"
categories = ["functional-programming"]
edition = "2018"
